package com.singgih.webservice.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-12-11T15:35:02.466+07:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://sample.webservice.singgih.com/", name = "HelloWebService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface HelloWebService {

    @WebResult(name = "return", targetNamespace = "http://sample.webservice.singgih.com/", partName = "return")
    @WebMethod
    public java.lang.String sayHello(
        @WebParam(partName = "guestname", name = "guestname")
        java.lang.String guestname
    );
}
